--- # Poggit-CI Manifest, Open the CI at https://poggit.pmmp.io/ci/DiscordBot-PMMP/DiscordBot
build-by-default: true
branches:
  - poggit
projects:
  DiscordBot:
    path: ""
    includeDirs:
      vendor: vendor
...